name: CI

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      TERRAFORM_STATE_TOKEN: ${{ secrets.TERRAFORM_STATE_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login registry-1.docker.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build --pull --rm -f "json-server/Dockerfile" -t stormhenkel/json-server:latest ./
        docker push stormhenkel/json-server:latest

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Install jq
      run: sudo apt-get install -y jq
    
    - name: Initialize Terraform
      run: terraform init
      working-directory: ./app-server

    - name: Initialize Validate
      run: terraform validate
      working-directory: ./app-server

    - name: Apply Terraform
      id: apply
      run: terraform apply -auto-approve 
      working-directory: ./app-server

    - name: Parse Terraform output
      id: parse_output
      run: |
        IP=$(terraform output -json | jq -r '.server_ip.value')
        echo "Server IP: $IP"
        echo "::set-output name=HOST_IP::$IP"
      working-directory: ./app-server

    - name: Add HOST IP to GitHub Secrets
      run: |
        echo $HOST_IP > /tmp/host_ip.txt
      env:
        HOST_IP: ${{ steps.parse_output.outputs.HOST_IP }}