name: CI

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      TERRAFORM_STATE_TOKEN: ${{ secrets.TERRAFORM_STATE_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    

    - name: login to docker registry
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: build and push docker image to registry
      uses: docker/build-push-action@v5
      with:
        context: json-server/
        push: true
        tags: stormhenkel/json-server:lts

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Install jq
      run: sudo apt-get install -y jq
    
    - name: Initialize Terraform
      run: terraform init
      working-directory: ./app-server

    - name: Initialize Validate
      run: terraform validate
      working-directory: ./app-server

    - name: Apply Terraform
      id: apply
      run: terraform apply -auto-approve 
      working-directory: ./app-server

    - name: Parse Terraform output
      id: parse_output
      run: |
        IP=$(terraform output -json | jq -r '.server_ip.value')
        echo "Server IP: $IP"
        echo "::set-output name=HOST_IP::$IP"
      working-directory: ./app-server

    - name: Add HOST IP to GitHub Secrets
      run: |
        echo $HOST_IP > /tmp/host_ip.txt
      env:
        HOST_IP: ${{ steps.parse_output.outputs.HOST_IP }}